Notebook Preparation

In [1]:
# Loading the necessary packages
import pandas as pd
import numpy as np

Data Extraction

In [3]:
# Import the electricity generation dataset

Generation_data = pd.read_csv("../Data/Raw/Generation.csv", sep=";")

Data Exploration and Transformation

In [4]:
# What does the dataset even look like...? Let's see!!!

Generation_data.head(5)

,Start date,End date,Biomass [MWh] Calculated resolutions,Hydropower [MWh] Calculated resolutions,Wind offshore [MWh] Calculated resolutions,Wind onshore [MWh] Calculated resolutions,Photovoltaics [MWh] Calculated resolutions,Other renewable [MWh] Calculated resolutions,Nuclear [MWh] Calculated resolutions,Lignite [MWh] Calculated resolutions,Hard coal [MWh] Calculated resolutions,Fossil gas [MWh] Calculated resolutions,Hydro pumped storage [MWh] Calculated resolutions,Other conventional [MWh] Calculated resolutions
0,"Jan 1, 2015","Jan 2, 2015","96,341.25","27,463.00","12,508.50","298,791.75","17,080.25","2,148.50","251,485.25","314,599.00","60,725.25","23,806.00","23,683.50","134,117.00"
1,"Jan 2, 2015","Jan 3, 2015","96,247.25","27,087.75","10,329.25","591,620.75","7,759.00","2,904.00","218,435.50","257,344.00","83,617.25","29,919.25","25,524.75","148,762.00"
2,"Jan 3, 2015","Jan 4, 2015","95,923.75","31,135.75","12,119.50","457,043.50","7,234.75","3,245.00","245,251.50","296,727.50","60,999.25","29,790.75","26,328.75","139,297.00"
3,"Jan 4, 2015","Jan 5, 2015","96,885.00","42,212.25","11,538.50","379,029.50","19,982.50","3,247.00","251,627.75","287,900.50","47,224.50","21,470.75","26,499.25","132,493.75"
4,"Jan 5, 2015","Jan 6, 2015","96,449.00","38,092.50","7,745.50","219,623.50","26,522.25","3,217.75","267,081.00","405,171.25","177,046.75","35,151.75","25,738.50","207,876.00"

In [8]:
Generation_data.tail(5)

,Start date,End date,Biomass [MWh] Calculated resolutions,Hydropower [MWh] Calculated resolutions,Wind offshore [MWh] Calculated resolutions,Wind onshore [MWh] Calculated resolutions,Photovoltaics [MWh] Calculated resolutions,Other renewable [MWh] Calculated resolutions,Nuclear [MWh] Calculated resolutions,Lignite [MWh] Calculated resolutions,Hard coal [MWh] Calculated resolutions,Fossil gas [MWh] Calculated resolutions,Hydro pumped storage [MWh] Calculated resolutions,Other conventional [MWh] Calculated resolutions
4013,"Dec 27, 2025","Dec 28, 2025","103,723.06","20,340.30","110,592.03","303,829.82","77,452.90","2,261.72",-,"156,948.39","51,236.84","224,893.49","8,045.42","45,004.56"
4014,"Dec 28, 2025","Dec 29, 2025","103,560.02","20,736.18","59,553.65","229,358.72","85,204.52","2,261.72",-,"150,221.84","61,464.75","231,171.83","17,181.98","47,558.55"
4015,"Dec 29, 2025","Dec 30, 2025","103,064.59","20,750.17","156,957.92","434,906.95","50,371.21","2,278.31",-,"176,356.99","74,284.68","223,454.87","14,756.24","46,222.64"
4016,"Dec 30, 2025","Dec 31, 2025","103,173.87","21,763.20","141,693.25","386,067.59","77,368.27","2,309.13",-,"158,299.77","58,695.58","205,462.78","32,314.31","48,612.35"
4017,"Dec 31, 2025","Jan 1, 2026","102,163.51","20,856.90","134,028.88","628,636.66","44,986.73","2,264.63",-,"128,036.94","77,415.91","199,029.49","15,188.50","47,587.95"

In [5]:
# Lets see the summary statistics of the dataset

Generation_data.describe()

,Start date,End date,Biomass [MWh] Calculated resolutions,Hydropower [MWh] Calculated resolutions,Wind offshore [MWh] Calculated resolutions,Wind onshore [MWh] Calculated resolutions,Photovoltaics [MWh] Calculated resolutions,Other renewable [MWh] Calculated resolutions,Nuclear [MWh] Calculated resolutions,Lignite [MWh] Calculated resolutions,Hard coal [MWh] Calculated resolutions,Fossil gas [MWh] Calculated resolutions,Hydro pumped storage [MWh] Calculated resolutions,Other conventional [MWh] Calculated resolutions
count,4018,4018,4018,4018,4018,4018,4018,4018,4018,4018,4018,4018,4018,4018
unique,4018,4018,3948,3966,4003,4014,4012,3524,3018,4013,4010,4012,3937,3951
top,"Jan 1, 2015","Jan 2, 2015","111,494.50","39,181.50","36,379.00","479,897.50","68,587.00","2,261.72",-,"385,517.25","49,637.50","21,659.25","21,776.50","31,213.50"
freq,1,1,3,2,2,2,2,5,702,2,2,2,2,2

In [6]:
# Lets see if there are any missing values in the dataset

Generation_data.isnull().sum()

Start date                                           0
End date                                             0
Biomass [MWh] Calculated resolutions                 0
Hydropower [MWh] Calculated resolutions              0
Wind offshore [MWh] Calculated resolutions           0
Wind onshore [MWh] Calculated resolutions            0
Photovoltaics [MWh] Calculated resolutions           0
Other renewable [MWh] Calculated resolutions         0
Nuclear [MWh] Calculated resolutions                 0
Lignite [MWh] Calculated resolutions                 0
Hard coal [MWh] Calculated resolutions               0
Fossil gas [MWh] Calculated resolutions              0
Hydro pumped storage [MWh] Calculated resolutions    0
Other conventional [MWh] Calculated resolutions      0
dtype: int64

In [7]:
# What are the datatypes of the columns in the dataset?

print(Generation_data.dtypes)

Start date                                           object
End date                                             object
Biomass [MWh] Calculated resolutions                 object
Hydropower [MWh] Calculated resolutions              object
Wind offshore [MWh] Calculated resolutions           object
Wind onshore [MWh] Calculated resolutions            object
Photovoltaics [MWh] Calculated resolutions           object
Other renewable [MWh] Calculated resolutions         object
Nuclear [MWh] Calculated resolutions                 object
Lignite [MWh] Calculated resolutions                 object
Hard coal [MWh] Calculated resolutions               object
Fossil gas [MWh] Calculated resolutions              object
Hydro pumped storage [MWh] Calculated resolutions    object
Other conventional [MWh] Calculated resolutions      object
dtype: object

In [ ]:
##  What I have noticed so far...

# Column names are too long, would be easier for analysis if there are simplified.
# The "End date" column is not necessary, the "Start date" column can just be named "Date" for simplicity.
# The "Nuclear [MWh] Calculated resolutions" column contains about 702 "-" charaters, which might affect future analysis.
# The data types are Objects, it would be nice to have the "Date" column as "Datetype", and the other columns as "Floats".

## I'd try to resolve these in the next steps....Let's gooo!!!!

In [9]:
# Making the column names easily readable

Generation_data.columns = [col.replace(' [MWh] Calculated resolutions', '').replace(' ', '_') for col in Generation_data.columns]
Generation_data.head(1)

,Start_date,End_date,Biomass,Hydropower,Wind_offshore,Wind_onshore,Photovoltaics,Other_renewable,Nuclear,Lignite,Hard_coal,Fossil_gas,Hydro_pumped_storage,Other_conventional
0,"Jan 1, 2015","Jan 2, 2015","96,341.25","27,463.00","12,508.50","298,791.75","17,080.25","2,148.50","251,485.25","314,599.00","60,725.25","23,806.00","23,683.50","134,117.00"

In [10]:
# Renaming the "Start date" column to "Date"

Generation_data.rename(columns={'Start_date': 'Date'}, inplace=True)

In [11]:
# Dropping the "End date" column

Generation_data.drop(columns=['End_date'], inplace=True)

In [12]:
# Quick peek at the dataset after the changes

Generation_data.head(1)

,Date,Biomass,Hydropower,Wind_offshore,Wind_onshore,Photovoltaics,Other_renewable,Nuclear,Lignite,Hard_coal,Fossil_gas,Hydro_pumped_storage,Other_conventional
0,"Jan 1, 2015","96,341.25","27,463.00","12,508.50","298,791.75","17,080.25","2,148.50","251,485.25","314,599.00","60,725.25","23,806.00","23,683.50","134,117.00"

In [13]:
# Screening the Entire DataFrame for ('-') characters and replacing them with a "0"

check = Generation_data.isin(['-']) 

if check.any().any():
    # If any occurrences are found
    print("Unwanted characters ('-') found in the DataFrame.")
    
    # Print the rows where '-' occurs
    print("Occurrences of '-' in the DataFrame:")
    print(Generation_data[check.any(axis=1)])
    
    # Replace All Occurrences of '-' with 0 in the Entire DataFrame
    Generation_data.replace('-', 0, inplace=True)
    print("All occurrences of '-' have been replaced with 0.")
else:
    # If no occurrences are found
    print("No unwanted characters ('-') found in the DataFrame.")

Unwanted characters ('-') found in the DataFrame.
Occurrences of '-' in the DataFrame:
              Date     Biomass Hydropower Wind_offshore Wind_onshore  \
3316  Jan 30, 2024  104,060.00  53,501.25    107,775.00   424,770.25
3317  Jan 31, 2024  102,696.00  54,212.25    118,063.25   492,575.50
3318   Feb 1, 2024  103,304.75  52,421.75     92,091.25   670,442.75
3319   Feb 2, 2024  104,253.50  51,035.75    124,865.50   747,270.25
3320   Feb 3, 2024  101,908.75  47,339.50    128,853.75   832,640.00
...            ...         ...        ...           ...          ...
4013  Dec 27, 2025  103,723.06  20,340.30    110,592.03   303,829.82
4014  Dec 28, 2025  103,560.02  20,736.18     59,553.65   229,358.72
4015  Dec 29, 2025  103,064.59  20,750.17    156,957.92   434,906.95
4016  Dec 30, 2025  103,173.87  21,763.20    141,693.25   386,067.59
4017  Dec 31, 2025  102,163.51  20,856.90    134,028.88   628,636.66

     Photovoltaics Other_renewable Nuclear     Lignite   Hard_coal  \
3316     76,415.50        3,854.25       -  229,037.50  115,430.75
3317     44,627.75        3,839.00       -  216,617.00  131,828.00
3318     67,201.50        4,054.25       -  176,399.50  130,314.75
3319     48,930.25        3,841.75       -  138,935.25  101,264.50
3320     51,887.25        3,549.25       -   88,819.75   88,512.75
...            ...             ...     ...         ...         ...
4013     77,452.90        2,261.72       -  156,948.39   51,236.84
4014     85,204.52        2,261.72       -  150,221.84   61,464.75
4015     50,371.21        2,278.31       -  176,356.99   74,284.68
4016     77,368.27        2,309.13       -  158,299.77   58,695.58
4017     44,986.73        2,264.63       -  128,036.94   77,415.91

      Fossil_gas Hydro_pumped_storage Other_conventional
3316  209,884.00            23,825.00          45,491.50
3317  201,816.25            29,429.00          46,041.00
3318  191,849.25            35,926.50          47,874.00
3319  172,273.50            20,640.75          45,434.75
3320  123,627.75            29,465.50          46,174.50
...          ...                  ...                ...
4013  224,893.49             8,045.42          45,004.56
4014  231,171.83            17,181.98          47,558.55
4015  223,454.87            14,756.24          46,222.64
4016  205,462.78            32,314.31          48,612.35
4017  199,029.49            15,188.50          47,587.95

[702 rows x 13 columns]
All occurrences of '-' have been replaced with 0.

In [14]:
# Formatting the data column to date type

Generation_data['Date'] = pd.to_datetime(Generation_data['Date'])

In [15]:
# Formatting the rest of the columns to float type

for col in Generation_data.columns:
    if col not in ["Date"]:
        # Remove commas before converting to float
        Generation_data[col] = Generation_data[col].astype(str).str.replace(",", "").astype("float32")

In [16]:
# Did the changes work? Let's see the summary statistics again

Generation_data.describe()

,Date,Biomass,Hydropower,Wind_offshore,Wind_onshore,Photovoltaics,Other_renewable,Nuclear,Lignite,Hard_coal,Fossil_gas,Hydro_pumped_storage,Other_conventional
count,4018,4018.000000,4018.000000,4018.000000,4.018000e+03,4018.000000,4018.000000,4018.000000,4018.000000,4018.00000,4018.000000,4018.000000,4018.000000
mean,2020-07-01 12:00:00,104485.171875,42226.683594,57745.972656,2.588976e+05,131559.062500,3660.592529,135788.671875,280143.656250,147397.21875,125253.132812,26132.058594,55121.839844
min,2015-01-01 00:00:00,85271.750000,20340.300781,171.500000,7.213750e+03,4906.250000,1408.250000,0.000000,49067.000000,5127.00000,14330.250000,4308.609863,14487.250000
25%,2017-10-01 06:00:00,98529.875000,34722.322266,24127.000000,1.105353e+05,47797.625000,2807.317566,52392.187500,212421.625000,65540.50000,67448.812500,20831.250000,33522.875000
50%,2020-07-01 12:00:00,105079.875000,41608.625000,52867.000000,2.010266e+05,119846.699219,3541.000000,161101.500000,295875.375000,126023.00000,110838.125000,26203.875000,38447.500000
75%,2023-04-01 18:00:00,110004.375000,48971.125000,87578.125000,3.564395e+05,195214.125000,4463.187500,210954.062500,356356.250000,218399.62500,171817.500000,31311.562500,46260.500000
max,2025-12-31 00:00:00,119807.250000,72365.250000,171228.234375,1.060474e+06,477677.250000,6207.000000,274628.500000,469374.750000,426636.50000,420208.000000,61197.750000,491341.000000
std,NaN,7271.868652,9657.073242,38656.382812,1.967137e+05,93084.156250,999.089355,90090.250000,92955.734375,94841.09375,74691.109375,7752.742188,43948.906250

In [17]:
# Lets see the datatypes of the columns again

print(Generation_data.dtypes)

Date                    datetime64[ns]
Biomass                        float32
Hydropower                     float32
Wind_offshore                  float32
Wind_onshore                   float32
Photovoltaics                  float32
Other_renewable                float32
Nuclear                        float32
Lignite                        float32
Hard_coal                      float32
Fossil_gas                     float32
Hydro_pumped_storage           float32
Other_conventional             float32
dtype: object

In [18]:
#another quick peek at the dataset after all the changes

Generation_data.head(5)

,Date,Biomass,Hydropower,Wind_offshore,Wind_onshore,Photovoltaics,Other_renewable,Nuclear,Lignite,Hard_coal,Fossil_gas,Hydro_pumped_storage,Other_conventional
0,2015-01-01,96341.25,27463.00,12508.50,298791.75,17080.25,2148.50,251485.25,314599.00,60725.25,23806.00,23683.50,134117.00
1,2015-01-02,96247.25,27087.75,10329.25,591620.75,7759.00,2904.00,218435.50,257344.00,83617.25,29919.25,25524.75,148762.00
2,2015-01-03,95923.75,31135.75,12119.50,457043.50,7234.75,3245.00,245251.50,296727.50,60999.25,29790.75,26328.75,139297.00
3,2015-01-04,96885.00,42212.25,11538.50,379029.50,19982.50,3247.00,251627.75,287900.50,47224.50,21470.75,26499.25,132493.75
4,2015-01-05,96449.00,38092.50,7745.50,219623.50,26522.25,3217.75,267081.00,405171.25,177046.75,35151.75,25738.50,207876.00

In [21]:
# Perfect! The dataset is now clean and ready for analysis.

Saving the transformed dataset

In [19]:
# Saving the cleaned dataset to a new CSV file

Generation_data.to_csv("../data/processed/generation_cleaned.csv", index=False)

In [20]:
# The electricity generation dataset has been successfully cleaned and saved as "generation_cleaned.csv" in the "processed" folder.